### ISSUE TITLE
Validation errors after upgrading to FHIR 5.0.0

### ISSUE THREAD

**Issue by baixiac** [DataTools4Heart/common-data-model#6]
Hi, just noticed that FHIR was upgraded to 5.0.0 from 4.0.1 and it looks very like the following error during startup is related to the `onfhir:r4` image being used. Can anyone shed some light on this, and does this mean the main branch will only work with the future `onfhir:r5` image?

```
i.o.r.c.FhirR4Configurator - Validating given FHIR foundation resources for base specification conformance ...
Exception in thread "main" io.onfhir.exception.InitializationException: Some of the given infrastructure resources (https://datatools4heart.eu/fhir/CapabilityStatement/hfr-health-data-store-capability-statement) of type CapabilityStatement does not conform to base FHIR specification! https://datatools4heart.eu/fhir/CapabilityStatement/hfr-health-data-store-capability-statement :: JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code '5.0.0' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/FHIR-version' or is nor active and selectable!)), (expression,JArray(List(JString(fhirVersion)))))),JObject(List((severity,JString(warning)), (code,JString(invalid)), (diagnostics,JString(Unknown or not processable ValueSet 'http://hl7.org/fhir/ValueSet/mimetypes' for validation, skipping code binding validation...)), (expression,JArray(List(JString(format[0])))))),JObject(List((severity,JString(warning)), (code,JString(invalid)), (diagnostics,JString(Unknown or not processable ValueSet 'http://hl7.org/fhir/ValueSet/mimetypes' for validation, skipping code binding validation...)), (expression,JArray(List(JString(patchFormat[0])))))),JObject(List((severity,JString(warning)), (code,JString(invalid)), (diagnostics,JString(Unknown or not processable ValueSet 'http://hl7.org/fhir/ValueSet/mimetypes' for validation, skipping code binding validation...)), (expression,JArray(List(JString(patchFormat[1])))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'DeviceAssociation' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[9].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'DeviceDispense' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[10].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'DeviceUsage' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[13].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'EncounterHistory' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[17].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'FormularyItem' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[22].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'GenomicStudy' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[23].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'ImagingSelection' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[29].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'Ingredient' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[35].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'InventoryItem' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[36].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'InventoryReport' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[37].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'MedicinalProductDefinition' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[50].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'NutritionIntake' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[55].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'NutritionProduct' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[57].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'PackagedProductDefinition' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[61].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'Permission' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[63].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'RegulatedAuthorization' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[71].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'RequestOrchestration' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[73].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'SubscriptionStatus' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[85].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'SubscriptionTopic' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[86].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'SubstanceDefinition' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[88].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'TestPlan' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[98].type)))))),JObject(List((severity,JString(error)), (code,JString(invalid)), (diagnostics,JString(Code binding failure, code 'Transport' is not defined in the ValueSet 'http://hl7.org/fhir/ValueSet/resource-types' or is nor active and selectable!)), (expression,JArray(List(JString(rest[0].resource[101].type)))))),JObject(List((severity,JString(warning)), (code,JString(invalid)), (diagnostics,JString(Constraint 'cpb-0' is not satisfied for the given value! Constraint Description: 'Name should be usable as an identifier for the module by machine processing applications such as code generation'. FHIR Path expression: 'name.matches('[A-Z]([A-Za-z0-9_]){0,254}')')), (expression,JArray(List(JString($this)))))),JObject(List((severity,JString(warning)), (code,JString(invalid)), (diagnostics,JString(Constraint 'dom-6' is not satisfied for the given value! Constraint Description: 'A resource should have narrative for robust management'. FHIR Path expression: 'text.`div`.exists()')), (expression,JArray(List(JString($this))))))
        at io.onfhir.config.BaseFhirConfigurator.validateGivenInfrastructureResources(BaseFhirConfigurator.scala:190)
        at io.onfhir.config.BaseFhirServerConfigurator.initializeServerPlatform(BaseFhirServerConfigurator.scala:105)
        at io.onfhir.config.FhirConfigurationManager$.initialize(FhirConfigurationManager.scala:55)
        at io.onfhir.Onfhir.<init>(Onfhir.scala:56)
        at io.onfhir.Onfhir$.apply(Onfhir.scala:226)
        at io.onfhir.r4.Boot$.delayedEndpoint$io$onfhir$r4$Boot$1(Boot.scala:18)
        at io.onfhir.r4.Boot$delayedInit$body.apply(Boot.scala:8)
        at scala.Function0.apply$mcV$sp(Function0.scala:42)
        at scala.Function0.apply$mcV$sp$(Function0.scala:42)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:98)
        at scala.App.$anonfun$main$1$adapted(App.scala:98)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
        at scala.App.main(App.scala:98)
        at scala.App.main$(App.scala:96)
        at io.onfhir.r4.Boot$.main(Boot.scala:8)
        at io.onfhir.r4.Boot.main(Boot.scala)
```

**Comment by YemreGurses** [comment]
Yes, sorry for inconvenience. We are currently working on that. It will be fixed soon. R5 will be used in the future.

**Comment by baixiac** [comment]
Thanks @YemreGurses, and feel free to close this.
